In [1]:
# importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [32]:
# importing the dataset that means that the data preprocessing parts started from here
dataset=pd.read_csv('/content/sample_data/Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [33]:
Y=dataset.iloc[:,-1].values
Y

array([1, 0, 1, ..., 1, 1, 0])

In [34]:
X=dataset.iloc[:,3:-1].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [35]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [36]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [37]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [39]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)

In [40]:
X_test=sc.fit_transform(X_test)

In [41]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [42]:
# initializing the ann
ann=tf.keras.models.Sequential()
# input and first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
# adding 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
# adding output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [43]:
# compiling the ann
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [44]:
# training the data
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.8124 - accuracy: 0.4236
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5425 - accuracy: 0.7977
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4573 - accuracy: 0.8057
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4394 - accuracy: 0.8087
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4286 - accuracy: 0.8171
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4170 - accuracy: 0.8192
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4126 - accuracy: 0.8265
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4047 - accuracy: 0.8305
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4168 - accuracy: 0.8230
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4132 - accura

In [28]:
ann.predict(X_test)

array([[0.23382586],
       [0.26491675],
       [0.11365959],
       ...,
       [0.10479352],
       [0.12325266],
       [0.22056165]], dtype=float32)

In [48]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

[[False]]


In [49]:
# this means that very low chance to leave the bank the answer of false is 1

from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=(ann.predict(X_test)>0.5)
np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1)

array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [50]:
confusion_matrix(Y_test,y_pred)

array([[1519,   76],
       [ 216,  189]])

In [51]:
accuracy_score(Y_test,y_pred)

0.854